- name: Create CNI dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: root
    group: containerd
  loop:
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Ship cni plugin config
  ansible.builtin.template:
    src: 10-containerd-net.conflist.j2
    dest: /etc/cni/net.d/10-containerd-net.conflist
    mode: "0440"

- name: Check cni version
  ansible.builtin.command:
    # Workaround until https://github.com/containernetworking/plugins/issues/1019 is fixed.
    # Don't forget to update also the following tasks (check stderr instead of stdout),
    # when the ticket is fixed.
    cmd: cat /opt/cni/version.txt
    # cmd: /opt/cni/bin/loopback --version
  register: cni_version_deployed
  changed_when: false
  ignore_errors: true
  check_mode: false # Check always the version, to make sure the variable is created

- name: Download cni package
  ansible.builtin.get_url:
    url: "{{ cni_dl_url }}"
    dest: "/tmp/cni-{{ cni_version }}.tar.gz"
    checksum: "{{ cni_sha256 }}"
    mode: "0444"
  notify: Remove cni download
  when: >
    cni_version_deployed.failed or
    not cni_version | string in cni_version_deployed.stdout_lines.0

- name: Unpack cni package
  ansible.builtin.unarchive:
    dest: /opt/cni/bin
    src: "/tmp/cni-{{ cni_version }}.tar.gz"
    mode: u=rwX,g=rX,o=
    owner: root
    group: containerd
    remote_src: true
  when: >
    cni_version_deployed.failed or
    not cni_version | string in cni_version_deployed.stdout_lines.0
  ignore_errors: "{{ ansible_check_mode }}"
  notify: Document version info
