# We don't want to deploy any CNI stuff at the moment, but to make kubelet and containerd happy,
# we have to initialize something. Therefore we deploy some dummy config, without any functionality.
# For now we only support host networking. If we need more, we have to deploy and configure it.
# https://github.com/containernetworking/cni

- name: create config dir
  ansible.builtin.file:
    path: /etc/cni/net.d
    state: directory
    mode: "0755"

# No service reload necessary - containerd will load it automatically
- name: ship dummy plugin config to make containerd and kubelet happy
  ansible.builtin.template:
    src: 99-dummy.conf
    dest: /etc/cni/net.d/99-dummy.conf
    mode: "0444"
