- name: Check current crictl version
  ansible.builtin.command:
    cmd: /usr/local/sbin/crictl --version
  register: crictl_version_deployed
  ignore_errors: true
  changed_when: false
  check_mode: false # Check always the version, to make sure the variable is created

- name: Download crictl
  ansible.builtin.get_url:
    url: "{{ crictl_dl_url }}"
    dest: /tmp/crictl-{{ crictl_version }}.tar.gz
    checksum: "{{ crictl_sha256 }}"
    mode: "0444"
  notify: Remove crictl download
  register: crictl_download
  when: >
    crictl_version_deployed.failed or
    not crictl_version | string in crictl_version_deployed.stdout

- name: Deploy crictl if necessary
  ansible.builtin.unarchive:
    src: /tmp/crictl-{{ crictl_version }}.tar.gz
    dest: /usr/local/sbin/
    remote_src: true
    owner: root
    group: containerd
    mode: "0750"
  when: >
    crictl_version_deployed.failed or
    not crictl_version | string in crictl_version_deployed.stdout
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ship crictl config
  ansible.builtin.template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    mode: "0440"
    owner: root
    group: containerd
