- name: Create directories for nerdctl
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    mode: "0750"
    owner: root
    group: containerd
  loop:
    - /etc/nerdctl

- name: Check current nerdctl version
  ansible.builtin.command:
    cmd: /usr/local/sbin/nerdctl --version
  register: nerdctl_version_deployed
  ignore_errors: true
  changed_when: false
  check_mode: false # Check always the version, to make sure the variable is created

- name: Download nerdctl
  ansible.builtin.get_url:
    url: "{{ nerdctl_dl_url }}"
    dest: /tmp/nerdctl-{{ nerdctl_version }}.tar.gz
    checksum: "{{ nerdctl_sha256 }}"
    mode: "0444"
  notify: Remove nerdctl download
  register: nerdctl_download
  when: >
    nerdctl_version_deployed.failed or
    not (nerdctl_version | string)[1:] in nerdctl_version_deployed.stdout

- name: Deploy nerdctl if necessary
  ansible.builtin.unarchive:
    src: /tmp/nerdctl-{{ nerdctl_version }}.tar.gz
    dest: /usr/local/sbin/
    remote_src: true
    owner: root
    group: containerd
    mode: "0750"
  when: >
    nerdctl_version_deployed.failed or
    not (nerdctl_version | string)[1:] in nerdctl_version_deployed.stdout
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ship nerdctl config
  ansible.builtin.template:
    src: nerdctl.toml.j2
    dest: /etc/nerdctl/nerdctl.toml
    mode: "0440"
    owner: root
    group: containerd
