- name: check current nerdctl version
  ansible.builtin.command:
    cmd: /usr/local/bin/nerdctl --version
  register: cur_nerdctl_version
  ignore_errors: true
  changed_when: false

- name: download nerdctl
  ansible.builtin.get_url:
    url: "{{ nerdctl_dl_url }}"
    dest: "/tmp/nerdctl-{{ nerdctl_version }}.tar.gz"
    checksum: "sha256:{{ nerdctl_sha256[custom_arch] }}"
    mode: 0444
  notify: remove nerdctl download
  when: cur_nerdctl_version.failed or not nerdctl_version in cur_nerdctl_version.stdout

- name: deploy nerdctl if necessary
  ansible.builtin.unarchive:
    src: "/tmp/nerdctl-{{ nerdctl_version }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
    owner: root
    group: root
    mode: 0555
  when: cur_nerdctl_version.failed or not nerdctl_version in cur_nerdctl_version.stdout
  ignore_errors: "{{ ansible_check_mode }}"

- name: create config dir
  ansible.builtin.file:
    path: /etc/nerdctl
    state: directory
    owner: root
    group: root
    mode: 0755

- name: ship nerdctl config
  ansible.builtin.template:
    src: nerdctl.toml
    dest: /etc/nerdctl/nerdctl.toml
    mode: 0444
  ignore_errors: "{{ ansible_check_mode }}"
