- name: Make sure, prometheus dirs exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/prometheus
    - /etc/prometheus/targets
    - /etc/prometheus/rules
    - /opt/prometheus/data

- name: Deploy prometheus config files and reload prometheus
  ansible.builtin.template:
    src: config.yml
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0440'
  notify: Reload prometheus

- name: Deploy container manifest
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/kubelet/manifests/prometheus.yml
    owner: root
    group: root
    mode: "0444"

- name: Wait for container to come up
  ansible.builtin.command:
    cmd: crictl ps -q --name prometheus
  register: prometheus_container
  until: prometheus_container.stdout != ""
  delay: 10
  retries: 100
  changed_when: false
  when: not ansible_check_mode

- name: Create/update dns entry
  community.general.cloudflare_dns:
    zone: ohr-mit-n.net
    record: prometheus
    type: A
    value: "{{ ansible_host }}"
    solo: true
    api_token: "{{ cloudflare_api_token }}"
