- name: Make sure, prometheus dirs exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/prometheus
    - /etc/prometheus/targets
    - /opt/prometheus/data

- name: Deploy prometheus config files and reload prometheus
  ansible.builtin.template:
    src: config.yml
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0440'
  notify: Reload prometheus

- name: Create prometheus blackbox scrape config
  ansible.builtin.template:
    src: "blackbox.yml"
    dest: "/etc/prometheus/blackbox.yml"
    mode: "0440"
    owner: root
    group: root

- name: Deploy container manifest
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/kubelet/manifests/prometheus.yml
    owner: root
    group: root
    mode: "0444"

- name: Wait for container to come up
  ansible.builtin.command:
    cmd: crictl ps -q --name prometheus
  register: prometheus_container
  until: prometheus_container.stdout != ""
  delay: 10
  retries: 100
  changed_when: false
  when: not ansible_check_mode

- name: Create/update dns entry
  community.general.cloudflare_dns:
    zone: ohr-mit-n.net
    record: prometheus
    type: A
    value: "{{ ansible_host }}"
    solo: true
    api_token: "{{ cloudflare_api_token }}"

- name: Ship caddy config
  ansible.builtin.copy:
    dest: "/etc/caddy/sites/{{ item.service }}"
    content: |2
      {{ item.from }}:443 {
        reverse_proxy {{ item.to }}
      }
    owner: root
    group: caddy
    mode: "0640"
  loop:
    - { service: "prometheus", from: "prometheus.ohr-mit-n.net", to: ":9090" }
  notify: Reload caddy
