grafana_version: 11.5.0

grafana_secret_key: "{{ lookup('community.general.bitwarden_secrets_manager', '15fbc648-3b6a-4391-9f02-b27a00c45be1').value }}"
grafana_user:
  admin:
    user: "{{ lookup('community.general.bitwarden_secrets_manager', '1c455af5-b905-443b-9b48-b27a00c4805c').value }}"
    pass: "{{ lookup('community.general.bitwarden_secrets_manager', 'c04c8c96-71b5-47a5-acf9-b27a00c4afe7').value }}"

grafana_datasources:
  - name: "Prometheus"
    type: "prometheus"
    url: "http://mimir.ohr-mit-n.net:9009/prometheus"
    uuid: "240D4F2C-75C1-4508-B4AB-D13888D1F841"
    default: true
    json_data:
      httpMethod: "POST"
      manageAlerts: true
      prometheusType: "Mimir"
      prometheusVersion: "2.9.1"
  - name: "Alertmanager"
    type: "alertmanager"
    url: "http://mimir.ohr-mit-n.net:9009/alertmanager"
    uuid: "79C52B9D-E8C8-4A48-AF7D-6A1869EE883B"
    default: false
    json_data:
      implementation: "prometheus"
