groups:
  - name: prometheus-server.rules
    rules:
      - alert: PrometheusTargetMissing
        expr: up == 0
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus target missing.
          description: "Target has disappeared: {{ $labels.job }} on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusConfigurationReloadFailure
        expr: prometheus_config_last_reload_successful != 1
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus configuration reload failure
          description: "Prometheus config reload error on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTooManyRestarts
        expr: changes(process_start_time_seconds{job=~"prometheus|alertmanager"}[5m]) > 4
        for: 0m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus too many restarts
          description: "Prometheus has restarted more than four times in the last 5 minutes on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusRuleEvaluationFailures
        expr: increase(prometheus_rule_evaluation_failures_total[3m]) > 0
        for: 0m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus rule evaluation failures
          description: >-
            Prometheus on {{ $labels.instance | stripDomain | stripPort | toUpper }} encountered {{ $value }} rule evaluation failures,
            leading to potentially ignored alerts.

      - alert: PrometheusTemplateTextExpansionFailures
        expr: increase(prometheus_template_text_expansion_failures_total[3m]) > 0
        for: 0m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus template text expansion failures
          description: "Prometheus on {{ $labels.instance | stripDomain | stripPort | toUpper }} encountered {{ $value }} template text expansion failures."

      - alert: PrometheusRuleEvaluationSlow
        expr: prometheus_rule_group_last_duration_seconds > prometheus_rule_group_interval_seconds
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus rule evaluation slow
          description: "Prometheus rule evaluation took more time than the scheduled interval.
            It indicates a slower storage backend access or too complex query.\n
            Instance: {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusNotificationsBacklog
        expr: min_over_time(prometheus_notifications_queue_length[10m]) > 0
        for: 0m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus notifications backlog
          description: "The Prometheus notification queue has not been empty for 10 minutes on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTargetEmpty
        expr: prometheus_sd_discovered_targets == 0
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus target empty
          description: "Prometheus has no target in service discovery on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTargetScrapingSlow
        expr: |
          prometheus_target_interval_length_seconds{interval="15s",quantile="0.9"} > 20 or
          prometheus_target_interval_length_seconds{interval="2m0s",quantile="0.9"} > 130
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus target scraping slow
          description: "Prometheus is scraping exporters slowly on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusLargeScrape
        expr: increase(prometheus_target_scrapes_exceeded_sample_limit_total[10m]) > 10
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus large scrape
          description: "Prometheus has many scrapes that exceed the sample limit on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTargetScrapeDuplicate
        expr: increase(prometheus_target_scrapes_sample_duplicate_timestamp_total[5m]) > 0
        for: 0m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus target scrape duplicate
          description: "Prometheus has many samples rejected due to duplicate timestamps but different values
            on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTsdbCheckpointCreationFailures
        expr: increase(prometheus_tsdb_checkpoint_creations_failed_total[1m]) > 0
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus TSDB checkpoint creation failures
          description: "Prometheus encountered {{ $value }} checkpoint creation failures on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTsdbCheckpointDeletionFailures
        expr: increase(prometheus_tsdb_checkpoint_deletions_failed_total[1m]) > 0
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus TSDB checkpoint deletion failures
          description: "Prometheus encountered {{ $value }} checkpoint deletion failures on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTsdbCompactionsFailed
        expr: increase(prometheus_tsdb_compactions_failed_total[1m]) > 0
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus TSDB compactions failed
          description: "Prometheus encountered {{ $value }} TSDB compactions failures on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTsdbHeadTruncationsFailed
        expr: increase(prometheus_tsdb_head_truncations_failed_total[1m]) > 0
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus TSDB head truncations failed
          description: "Prometheus encountered {{ $value }} TSDB head truncation failures on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTsdbReloadFailures
        expr: increase(prometheus_tsdb_reloads_failures_total[1m]) > 0
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus TSDB reload failures
          description: "Prometheus encountered {{ $value }} TSDB reload failures on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTsdbWalCorruptions
        expr: increase(prometheus_tsdb_wal_corruptions_total[1m]) > 0
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus TSDB WAL corruptions
          description: "Prometheus encountered {{ $value }} TSDB WAL corruptions on {{ $labels.instance | stripDomain | stripPort | toUpper }}"

      - alert: PrometheusTsdbWalTruncationsFailed
        expr: increase(prometheus_tsdb_wal_truncations_failed_total[1m]) > 0
        for: 5m
        labels:
          severity: P3
          service: prometheus
        annotations:
          summary: Prometheus TSDB WAL truncations failed
          description: "Prometheus encountered {{ $value }} TSDB WAL truncation failures on {{ $labels.instance | stripDomain | stripPort | toUpper }}"
