- name: deploy container manifest
  ansible.builtin.template:
    src: netatmo-exporter.yml
    dest: /opt/kubelet/manifests/netatmo-exporter.yml
    owner: root
    group: root
    mode: "0440"

- name: wait for container to come up
  ansible.builtin.command:
    cmd: crictl ps -q --name netatmo-exporter
  register: netatmo_exporter_container
  until: netatmo_exporter_container.stdout != ""
  delay: 10
  retries: 100
  changed_when: false
  when: not ansible_check_mode
