- name: Reload prometheus
  ansible.builtin.shell:
    cmd: kill -SIGHUP $(pidof prometheus)
  args:
    executable: /bin/bash
  changed_when: true

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
