{{ ansible_managed | comment }}
[poller]
  debug = false
  quiet = false
  plugins = []

[prometheus]
  disable = false
  http_listen = "{{ ansible_host }}:9130"
  report_errors = true
  dead_ports = false

[influxdb]
  disable = true

# Keep it for later
[loki]
  disable = true
  url = ""
  user       = ""
  pass       = ""
  verify_ssl = false
  tenant_id  = ""
  interval   = "2m"
  timeout    = "10s"

[datadog]
  enable = false

[webserver]
  enable = false

[unifi]
  dynamic = false

[unifi.defaults]
  url = "https://{{ ansible_host }}:8443"
  user = "{{ unifi_monitoring.user }}"
  pass = "{{ unifi_monitoring.pass }}"
  sites = ["all"]
  timeout = "30s"
  save_sites = true
  hash_pii = false
  save_ids = false
  save_events = false
  save_alarms = false
  save_anomalies = false
  save_dpi = false
  save_rogue = false
  verify_ssl = false
  ssl_cert_paths = []
