---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    pi4-r01-s04:
      ansible_host: 10.20.30.88
    pi4-r01-s06:
      ansible_host: 10.20.30.89
    pi4-r01-s08:
      ansible_host: 10.20.30.114
    pi4-r01-gas:
      ansible_host: 10.20.30.87
    pi5-autodarts:
      ansible_host: 10.20.30.98
    htznr-ollama:
      ansible_host: 2a01:4f9:c012:816d::1
    htznr-ollama-intel:
      ansible_host: 2a01:4f9:c013:2b8::1
