{
 "title": "Netatmo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Battery",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "netatmo_sensor_battery_percent", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Wifi Signal Wohnzimmer",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_sensor_wifi_signal_strength",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "RF Signal",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_sensor_rf_signal_strength",
     "legendFormat": "{{module}}"
    }
   ]
  },
  { "title": "Outdoor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "netatmo_sensor_temperature_celsius{module=\"Terrasse\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "fatcloud-windrose-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "netatmo_sensor_wind_direction_degrees{module=\"Windmesser\"}",
     "legendFormat": "{{direction}}"
    },
    {
     "expr": "netatmo_sensor_wind_strength_kph{module=\"Windmesser\"}",
     "legendFormat": "{{strength}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "netatmo_sensor_humidity_percent{module=\"Terrasse\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "netatmo_sensor_rain_amount_mm{module=\"Regenmesser\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  { "title": "Wohzimmer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "netatmo_sensor_temperature_celsius{module=\"Wohnzimmer\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "netatmo_sensor_co2_ppm{module=\"Wohnzimmer\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "netatmo_sensor_humidity_percent{module=\"Wohnzimmer\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Noise",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "netatmo_sensor_noise_db{module=\"Wohnzimmer\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  { "title": "Schlafzimmer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "netatmo_sensor_temperature_celsius{module=\"Schlafzimmer\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "netatmo_sensor_co2_ppm{module=\"Schlafzimmer\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "netatmo_sensor_humidity_percent{module=\"Schlafzimmer\"}",
     "legendFormat": "{{module}}"
    }
   ]
  }
 ]
}