- name: Create directories for private-gpt
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: 100 # as defined in the container
    group: 65534 # as defined in the container
  loop:
    - /opt/private-gpt/data

- name: Deploy container manifest
  ansible.builtin.template:
    src: private-gpt.yml
    dest: /opt/kubelet/manifests/private-gpt.yml
    owner: root
    group: root
    mode: "0440"
  no_log: true

- name: Wait for container to come up
  ansible.builtin.command:
    cmd: crictl ps -q --name "^private-gpt$"
  register: private_gpt_container
  until: private_gpt_container.stdout != ""
  delay: 10
  retries: 100
  changed_when: false
  when: not ansible_check_mode

- name: Create/update dns entry
  community.general.cloudflare_dns:
    zone: ohr-mit-n.net
    record: pgpt
    type: A
    value: "{{ ansible_host }}"
    solo: true
    api_token: "{{ cloudflare_api_token }}"

- name: Ship caddy config
  ansible.builtin.copy:
    dest: "/etc/caddy/sites/{{ item.service }}"
    content: |2
      {{ item.from }}:443 {
        reverse_proxy {{ item.to }}
      }
    owner: root
    group: caddy
    mode: "0640"
  loop:
    - { service: "private-gpt", from: "pgpt.ohr-mit-n.net", to: ":8001" }
  notify: Reload caddy
