# Installation was done via script: `bash <(curl -sL get.autodarts.io)`
# Original docs: https://autodarts.diy/getting-started/installation/

- name: Deploy dartlight service
  ansible.builtin.include_tasks: dartlight.yml

- name: Create/update dns entry
  community.general.cloudflare_dns:
    zone: ohr-mit-n.net
    record: autodarts
    type: A
    value: "{{ ansible_host }}"
    solo: true
    api_token: "{{ cloudflare_api_token }}"
