- name: Create directories for paperless-ai
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: paperless
    group: paperless
  loop:
    - /opt/paperless-ai
    - /opt/paperless-ai/data

- name: Deploy container manifest
  ansible.builtin.template:
    src: paperless-ai.yml
    dest: /opt/kubelet/manifests/paperless-ai.yml
    owner: root
    group: root
    mode: "0440"
  no_log: true

- name: Wait for container to come up
  ansible.builtin.command:
    cmd: crictl ps -q --name "^paperless-ai$"
  register: paperless_ai_container
  until: paperless_ai_container.stdout != ""
  delay: 10
  retries: 100
  changed_when: false
  when: not ansible_check_mode

- name: Create/update dns entry
  community.general.cloudflare_dns:
    zone: ohr-mit-n.net
    record: paperless-ai
    type: A
    value: "{{ ansible_host }}"
    solo: true
    api_token: "{{ cloudflare_api_token }}"
