{{ ansible_managed | comment }}
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    role: redis
spec:
  hostNetwork: true
  containers:
    - name: redis
      image: docker.io/library/redis:{{ redis_version }}
      args: ["--bind 127.0.0.1 -::1"]
      volumeMounts:
        - mountPath: /data
          name: redis-data
  volumes:
    - name: redis-data
      hostPath:
        path: /opt/redis/data
