{{ ansible_managed | comment }}
global:
  scrape_interval: 30s

remote_write:
  - url: https://mimir.ohr-mit-n.net/api/v1/push

storage:
  tsdb:
    out_of_order_time_window: 10s

#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
#        - {{ inventory_hostname_short }}:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets:
       - 127.0.0.1:9090

  - job_name: 'node-exporter'
    static_configs:
    - targets:
{% for host in groups['all']| sort %}
      - {{ hostvars[host].ansible_host }}:9100
{% endfor %}

  - job_name: 'unifi-exporter'
    static_configs:
    - targets:
       - unifi.ohr-mit-n.net:9130

  - job_name: 'netatmo-exporter'
    static_configs:
    - targets:
       - {{ ansible_host }}:9210

  - job_name: 'mqtt-exporter'
    static_configs:
    - targets:
       - mqtt.ohr-mit-n.net:9000

  - job_name: 'http_ping'
    scrape_interval: 120s
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - blackbox.yml
    relabel_configs:
      - source_labels:
          - __schema
          - __address__
          - __path
        separator: ''
        target_label: __param_target
      - source_labels: [__hostname]
        target_label: __param_hostname
      - source_labels: [__hostname]
        target_label: service
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
      - target_label: blackbox_instance
        replacement: {{ inventory_hostname }}
