{{ ansible_managed | comment }}
global:
  scrape_interval: 30s

rule_files:
  - '/etc/prometheus/rules/*.yml'

#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
#        - {{ inventory_hostname_short }}:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets:
       - {{ ansible_host }}:9090

  - job_name: 'node-exporter'
    static_configs:
    - targets:
{% for host in groups['all']| sort %}
      - {{ hostvars[host].ansible_host }}:9100
{% endfor %}

  - job_name: 'unifi-exporter'
    static_configs:
    - targets:
       - unifi.ohr-mit-n.net:9130

  - job_name: 'netatmo-exporter'
    static_configs:
    - targets:
       - {{ ansible_host }}:9210

#  - job_name: 'alertmanager'
#    static_configs:
#    - targets:
#       - {{ inventory_hostname_short }}:9093
