{{ ansible_managed | comment }}
apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    role: prometheus
spec:
  hostNetwork: true
  volumes:
    - name: prometheus-config
      hostPath:
        path: /etc/prometheus
    - name: prometheus-data
      hostPath:
        path: /opt/prometheus/data
  containers:
    - name: prometheus
      image: quay.io/prometheus/prometheus:{{ prometheus_version }}
      args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --log.level=info
        - --web.listen-address={{ ansible_host }}:9090
        - --web.enable-admin-api
        - --web.enable-lifecycle
        - --agent
        - --storage.agent.path=/prometheus/agent
      volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-config
        - mountPath: /prometheus
          name: prometheus-data
      securityContext:
        runAsUser: 0
        runAsGroup: 0
