- name: Create mimir directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: root
    group: root
  loop:
    - /etc/mimir
    - /opt/mimir/data
    - /opt/mimir/data/alerts
    - /opt/mimir/data/rules/anonymous

- name: Deploy mimir config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/mimir/{{ item }}"
    mode: "0640"
    owner: root
    group: root
  notify:
    - Restart mimir
    - Check mimir
  ignore_errors: "{{ ansible_check_mode }}"
  loop:
    - config.yml
    - alertmanager.yml

- name: Ship alerting rules
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/mimir/data/rules/anonymous/"
    owner: root
    group: root
    mode: '0444'
  with_fileglob:
    - ../files/rules/*.yml

- name: Create static pod manifest
  ansible.builtin.template:
    src: mimir.yml
    dest: "/opt/kubelet/manifests/mimir.yml"
    mode: "0440"
    owner: root
    group: root
  notify:
    - Check mimir

- name: Create/update dns entry
  community.general.cloudflare_dns:
    zone: ohr-mit-n.net
    record: mimir
    type: A
    value: "{{ ansible_host }}"
    solo: true
    api_token: "{{ cloudflare_api_token }}"
