{{ ansible_managed | comment }}
apiVersion: v1
kind: Pod
metadata:
  name: unifi-controller
  labels:
    role: unifi-controller
spec:
  hostNetwork: true
  volumes:
    - name: config
      hostPath:
        path: /opt/unifi-controller/config
  containers:
    - name: unifi-controller
      image: lscr.io/linuxserver/unifi-controller:{{ unifi_controller_version }}
      env:
        - name: TZ
          value: "UTC"
      volumeMounts:
        - mountPath: /config
          name: config
