- name: Create user for paperless
  ansible.builtin.user:
    name: "paperless"
    home: "/opt/paperless"
    system: true
  register: paperless_user

- name: Create directories for paperless
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: paperless
    group: paperless
  loop:
    - /opt/paperless/data
    - /opt/paperless/media
    - /opt/paperless/export
    - /opt/paperless/consume

- name: Deploy container manifest
  ansible.builtin.template:
    src: paperless.yml
    dest: /opt/kubelet/manifests/paperless.yml
    owner: root
    group: root
    mode: "0440"
  no_log: true

- name: Wait for container to come up
  ansible.builtin.command:
    cmd: crictl ps -q --name "^paperless$"
  register: paperless_container
  until: paperless_container.stdout != ""
  delay: 10
  retries: 100
  changed_when: false
  when: not ansible_check_mode

- name: Create/update dns entry
  community.general.cloudflare_dns:
    zone: ohr-mit-n.net
    record: paperless
    type: A
    value: "{{ ansible_host }}"
    solo: true
    api_token: "{{ cloudflare_api_token }}"

- name: Deploy HP scan target
  ansible.builtin.include_tasks: hp-to-scan.yml

- name: Deploy paperless-ai
  ansible.builtin.include_tasks: paperless-ai.yml
