- name: make sure, mosquitto dirs exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/mosquitto
    - /opt/mosquitto/data

- name: deploy mosquitto config files and reload mosquitto
  ansible.builtin.template:
    src: mosquitto.conf
    dest: /etc/mosquitto/mosquitto.conf
    owner: root
    group: root
    mode: '0440'
  notify: reload mosquitto

- name: deploy container manifest
  ansible.builtin.template:
    src: mosquitto.yml
    dest: /opt/kubelet/manifests/mosquitto.yml
    owner: root
    group: root
    mode: 0444

- name: wait for container to come up
  ansible.builtin.command:
    cmd: crictl ps -q --name mosquitto
  register: mosquitto_container
  until: mosquitto_container.stdout != ""
  delay: 10
  retries: 100
  changed_when: false
  when: not ansible_check_mode

- name: create/update dns entry
  community.general.cloudflare_dns:
    zone: ohr-mit-n.net
    record: mqtt
    type: A
    value: "{{ ansible_host }}"
    solo: true
    api_token: "{{ cloudflare_api_token }}"
