route:
  group_by: ['alertname']
  group_interval: 5m
  group_wait: 1m
  repeat_interval: 24h
  receiver: 'pushover'
  routes:
    - receiver: heartbeat
      matchers:
        - alertname = MonitoringHeartbeatAlert
      group_interval: 1m
      group_wait: 0s
      repeat_interval: 1m

receivers:
  - name: 'pushover'
    pushover_configs:
      - send_resolved: true
        user_key: {{ alertmanager.pushover_user_key }}
        token: {{ alertmanager.pushover_token }}
  - name: 'heartbeat'
    webhook_configs:
      - url: 'https://hc-ping.com/{{ alertmanager.healthcheck_uuid }}'
        send_resolved: true
