- name: create config dir
  ansible.builtin.file:
    state: directory
    path: /etc/unifi-exporter
    owner: root
    group: root
    mode: 0755

- name: deploy config file
  ansible.builtin.template:
    src: unpoller.toml
    dest: /etc/unifi-exporter/unpoller.toml
    mode: 0640
    owner: root
    group: root
  notify: restart unifi-exporter

- name: deploy container manifest
  ansible.builtin.template:
    src: unifi-exporter.yml
    dest: /opt/kubelet/manifests/unifi-exporter.yml
    owner: root
    group: root
    mode: 0444

- name: wait for container to come up
  ansible.builtin.command:
    cmd: crictl ps -q --name unifi-exporter
  register: unifi_exporter_container
  until: unifi_exporter_container.stdout != ""
  delay: 5
  retries: 60
  changed_when: false
  when: not ansible_check_mode
