name: Build-RPi-Image-64bit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          path: ./rpi-k3s
          
      - uses: actions/checkout@v3
        with:
          repository: RPi-Distro/pi-gen
          ref: arm64
          path: ./pi-gen
        
      - name: set version
        run: echo "IMAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER.arm64" >> $GITHUB_ENV
          
      - name: make sure only the lite image is created (skip stages 3-5)
        run: |
          touch ./pi-gen/stage3/SKIP ./pi-gen/stage4/SKIP ./pi-gen/stage5/SKIP
          touch ./pi-gen/stage4/SKIP_IMAGES ./pi-gen/stage5/SKIP_IMAGES
      - name: hotfix for apt issue https://github.com/actions/runner-images/issues/675
        run: sudo sed -i 's/azure\./de\./' /etc/apt/sources.list
      - name: install build dependencies
        run: sudo apt-get update && sudo apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx gpg pigz
        
      - name: build the Raspbian OS Lite image
        run: cd ./pi-gen && sudo ./build.sh -c ../rpi-k3s/pi-gen/config
        
      - name: upload image
        uses: actions/upload-artifact@v3
        with:
          name: raspberry_pi_os-lite-${{ env.IMAGE_VERSION }}.img
          path: ./pi-gen/work/*raspberry*/export-image/*-raspberry_pi_os-lite.img
