name: Build-RPi-Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out pi-gen repo
      - uses: actions/checkout@master
        with:
          name: RPi-Distro/pi-gen

      # Runs a single command using the runners shell
      - name: install dependencies
        run: sudo apt install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx
