name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set version
        run: |
          echo "VERSION_CONTAINER=1-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Set up QEMU for arm64 support
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
              
      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./gas-meter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gas-meter:${{ env.VERSION_CONTAINER }}
